numbers = [5, 6, 7, 8, 9, 2, 2]

print(numbers)
numbers.append(13)
print(numbers.count(2))
print(numbers)
numbers.insert(2, 4)
print(numbers)
numbers.remove(5)
print(numbers)
numbers.pop()
print(numbers)
numbers.sort()
print(numbers)
numbers.clear()
print(numbers)
print(50 in numbers)
